M48
; DRILL file KiCad 10.0.2 date 2026-05-18T13:32:20
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-18T13:32:20+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.2
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X150.0Y-69.8
T2
X108.5Y-78.0
X120.5Y-137.5
X179.5Y-137.5
X191.5Y-78.0
M30
